name: Tests

# TODO: uncomment this when ready to release
# on:
#   push:
#     tags:
#       - '**'
on: [push]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-darwin:
    name: Build Darwin
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install xcodegen via Homebrew for building xcode project
        run: brew install xcodegen
      -
        name: Generate an Xcode project from a spec
        run: xcodegen
      -
        name: Build Xcode project
        run: xcodebuild
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/Debug/WakaTime.app

  sign:
    name: Sign Apple binaries
    needs: [build-darwin]
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: WakaTime.app/
      # - 
      #   name: Move app to WakaTime.app
      #   shell: bash
      #   run: |
      #     mkdir -p ./build/WakaTime.app
      #     mv build/* ./build/WakaTime.app
      -
        name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - 
        name: Codesign app bundle
        run: /usr/bin/codesign --force -s "WakaTime" --options runtime WakaTime.app -v
      - 
        name: Notarize app bundle
        # Extract the secrets we defined earlier as environment variables
        env:
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.AC_USERNAME }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.AC_PASSWORD }}
        run: |
          # Store the notarization credentials so that we can prevent a UI password dialog
          # from blocking the CI

          echo "Create keychain profile"
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"

          # We can't notarize an app bundle directly, but we need to compress it as an archive.
          # Therefore, we create a zip file containing our app bundle, so that we can send it to the
          # notarization service

          echo "Creating temp notarization archive"
          ditto -c -k --keepParent "WakaTime.app" "WakaTime.zip"

          # Here we send the notarization request to the Apple's Notarization service, waiting for the result.
          # This typically takes a few seconds inside a CI environment, but it might take more depending on the App
          # characteristics. Visit the Notarization docs for more information and strategies on how to optimize it if
          # you're curious

          echo "Notarize app"
          xcrun notarytool submit "WakaTime.zip" --keychain-profile "notarytool-profile" --wait

          # Finally, we need to "attach the staple" to our executable, which will allow our app to be
          # validated by macOS even when an internet connection is not available.
          echo "Attach staple"
          xcrun stapler staple "WakaTime.app"
      # -
      #   name: Move app
      #   run: |
      #     mkdir ./signed
      #     mv ./WakaTime.app ./signed/
      # - 
      #   name: Zip app
      #   uses: vimtor/action-zip@v1
      #   with:
      #     files: WakaTime.app
      #     dest: ./signed/WakaTime.zip
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: WakaTime.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-darwin, sign]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Get related pull request
        uses: 8BitJonny/gh-get-current-pr@1.4.0
        id: changelog-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Prepare changelog
      #   id: changelog
      #   run: |
      #     changelog="${{ steps.changelog-release.outputs.pr_body }}"
      #     ./bin/prepare_changelog.sh $(echo ${GITHUB_REF#refs/heads/}) "$changelog"
      -
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: signed/
      -
        name: Prepare release assets
        run: ./bin/prepare_assets.sh
      -
        name: "Create release"
        uses: softprops/action-gh-release@master
        with:
          # name: ${GITHUB_REF##*/}
          # tag_name: ${GITHUB_REF##*/}``
          name: v0.1.0-test.1
          tag_name: v0.1.0-test.1
          # body: "## Changelog\n${{ steps.changelog.outputs.changelog }}"
          prerelease: true
          target_commitish: ${{ github.sha }}
          draft: true
          files: ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
